name: Android CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # Run tests for the composeApp module
      - name: Run Unit Tests
        run: ./gradlew :composeApp:testReleaseUnitTest

      - name: Decode Keystore
        # We put the key inside composeApp since that's where the Android build happens
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > composeApp/release.jks

      - name: Build Release Bundle (AAB)
        # Note the :composeApp: prefix
        run: ./gradlew :composeApp:bundleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          # Path updated to point inside the composeApp build folder
          path: composeApp/build/outputs/bundle/release/*.aab
          retention-days: 5
